### ISSUE TITLE
Is it possible to use the your service with third party clients ? 

### ISSUE THREAD

**Issue by F3000** [ncarlier/feedpushr#11]
I think of the ios App "Fiery Feeds"  . 

Do i need feedpushr and reeder or can feedpushr installed seperatly ?

Do you have a demo instace of feedpushr ?

**Comment by ncarlier** [comment]
Hi,

I'm afraid it's not that simple.
Feedpusher is not a RSS reader (such as [Fiery Feeds](https://apps.apple.com/fr/app/fiery-feeds-rss-reader/id1158763303) or [Reeder](https://reederapp.com/)) but "only" a RSS aggregator.
Feedpushr is able to push feeds to external systems having an API (Twitter, Mastodon, Readflow, ...). Fiery Feeds and Reeder are mobile/desktop apps without such API.

Speaking about news reader, Feedpushr was initially designed to be a RSS aggregator for [readflow](https://readflow.app). It's a general purpose news reader (not only for RSS feeds).

I deployed a sandbox of Feedpushr [here](https://feedpushr.alwaysdata.net/ui). If you want you can test it with readflow: https://about.readflow.app/docs/en/third-party/create/feedpushr/

**Comment by F3000** [comment]
Hi , 

thanks for the answer. But in can use Fiery Feeds when the developer build on your API ? 

It should be similar to nextcloud news , without having the rest of nextcloud right? 


Question to the API: 

Is it possible to 
- rename 
- delete 
- add 
- Tagging 
- move feeds between categories 

Can you send me a screenshot of the Lay-out when some feeds are added ? 

Thanks

**Comment by ncarlier** [comment]
Hi,

Feedpushr do not store articles in memory. New items are simply sent to another service that would store and consume them. Readflow/Twitter/Mastodon are this kind of service.

Fiery Feeds relies on other services to synchronize articles and feed with them. Linking Fiery Feeds directly with Feedpushr is not relevant because it will only concern the feeds and not the articles. You should have a third-party service used to store and provide articles to Fiery Feeds.

Speaking about Feedpushr features you can rename/delete/add and tags feeds.
You can find Feedpushr screenshots here: https://about.readflow.app/docs/en/third-party/create/feedpushr/
A demo is also available here: https://feedpushr.alwaysdata.net/ui/#/feeds
