### ISSUE TITLE
[Feature request] throttling the number of output per second

### ISSUE THREAD

**Issue by lucmichalski** [ncarlier/feedpushr#22]
Hi again,

Hope you are still all well !

I have developed a couple of plugins that require to throttle the output.

For example, I have written a plugin twitter-selenium. It launch one chrome instance but it needs to wait that one tweet is written/sent before having another tweet to be triggered.

Also, this apply for the yake module, if too much requests are sent to the service, it makes the rest service unavailable quickly because we do not have an option to throttle the output.

This feature is really important as it gonna be required for many potential plugins.

Thanks again if you can push that feature.

Cheers,
Luc

**Comment by ncarlier** [comment]
Hi,
I just added a new configuration parameter to add delay  on aggregators fan-out. This can mitigate the load due to the parallelisation (https://github.com/ncarlier/feedpushr/commit/096d1a8a0498604f94e8599b502ad9111938c1e9).
In a future release I need to review pipeline internals in order to have a better control on filters and outputs throttling.

**Comment by lucmichalski** [comment]
awesome :-) waiting for the last chunk of changes with such impatience ^^

**Comment by ncarlier** [comment]
Hi,

just a quick status about this issue. A refactoring is needed to solve this issue.
This refactoring is ongoing, but it is quite significant. Significant enough to trigger a v3.
I will take advantage of this work to include some new features:
- Place the filters under the outputs. An output will have its own filter chain.
- Use a goroutine per output in order to fine tune the throttling
- And a RSS explorer

I would also like to give the possibility to configure the recovery time per stream. But maybe for the 3.1 ;)

**Comment by lucmichalski** [comment]
Awesome ! Awessome ! Not enough words to describe how awesome this refactoring gonna be. :-)

By a RSS Explorer, do you mean a search engine to search them ? 
If yes, here is an example: https://gist.github.com/lucmichalski/0495ea796ef8576b448aa17278ff0e02

Thanks again.

**Comment by ncarlier** [comment]
Hi,

v3 RC1 is released. This release include:

- Major internal refactoring
- Improve control over output parallelism (Concurrency should be less aggressive)
- Put filters under outputs
- Import OPML file in background
- Find new RSS feeds to subscribe thanks to the explorer
- Simplify plugins design (⚠️ this implies small changes for custom plugins)
- Update dependencies

Feedbacks are very welcome 😃
