### ISSUE TITLE
OIDC client_id and secret parameters

### ISSUE THREAD

**Issue by nikeshpatel** [ncarlier/feedpushr#84]
I'm trying to setup OpenID auth (via Google) for feedpushr, but I noticed that the only parameter requested for setup is FP_AUTHN (for the issuer URL), whereas OIDC additionally requires a client id and secret (and the redirect URI I guess) to complete the flow.

Is there a way to pass these to feedpushr on start up like FP_AUTHN, or is the recommended pattern to clone the repo and make the modifications locally? If the later, can you point me to where the secret is set in the code + the redirect URI format? I've found that the client_id is set to 'feedpushr-ui' so that I can change.

Thank you for creating feedpushr btw, it's a great app that has saved me tons of time - I appreciate the work you've put into it!

**Comment by ncarlier** [comment]
Hi, thank you for your interest in the project!

You right, the `client_id` hard-coded ([here](https://github.com/ncarlier/feedpushr/blob/master/ui/src/context/AuthenticationContext.tsx#L32)). It's a problem. I will fix that in the next release. You don't need a `client_secret` because the client (the UI) is public ([usage with Google](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow)).

**Comment by ncarlier** [comment]
You can user the `--client-id` parameter to configure the UI cleint_id.
